//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadoryx.Lang.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cadoryx.Lang.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add layer.
        /// </summary>
        public static string AddLayer {
            get {
                return ResourceManager.GetString("AddLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add material.
        /// </summary>
        public static string AddMaterial {
            get {
                return ResourceManager.GetString("AddMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add part.
        /// </summary>
        public static string AddPart {
            get {
                return ResourceManager.GetString("AddPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add point.
        /// </summary>
        public static string AddPoint {
            get {
                return ResourceManager.GetString("AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular deviation.
        /// </summary>
        public static string AngularDeviation {
            get {
                return ResourceManager.GetString("AngularDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antialiasing.
        /// </summary>
        public static string Antialiasing {
            get {
                return ResourceManager.GetString("Antialiasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings applied..
        /// </summary>
        public static string ApplicationSettingsApplied {
            get {
                return ResourceManager.GetString("ApplicationSettingsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply instance placement.
        /// </summary>
        public static string ApplyPlacement {
            get {
                return ResourceManager.GetString("ApplyPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply properties.
        /// </summary>
        public static string ApplyProperties {
            get {
                return ResourceManager.GetString("ApplyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string AxisX {
            get {
                return ResourceManager.GetString("AxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string AxisY {
            get {
                return ResourceManager.GetString("AxisY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axonometric.
        /// </summary>
        public static string Axonometric {
            get {
                return ResourceManager.GetString("Axonometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary STL.
        /// </summary>
        public static string BinaryStl {
            get {
                return ResourceManager.GetString("BinaryStl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a feature and choose a boolean operation..
        /// </summary>
        public static string BooleanInstruction {
            get {
                return ResourceManager.GetString("BooleanInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum bounds.
        /// </summary>
        public static string BoundsMaximum {
            get {
                return ResourceManager.GetString("BoundsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum bounds.
        /// </summary>
        public static string BoundsMinimum {
            get {
                return ResourceManager.GetString("BoundsMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By layer.
        /// </summary>
        public static string ByLayer {
            get {
                return ResourceManager.GetString("ByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadoryx.
        /// </summary>
        public static string Cadoryx {
            get {
                return ResourceManager.GetString("Cadoryx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadoryx document (*.cadoryx)|*.cadoryx.
        /// </summary>
        public static string CadoryxDocumentFilter {
            get {
                return ResourceManager.GetString("CadoryxDocumentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadoryx documents (*.cadoryx)|*.cadoryx|All files (*.*)|*.*.
        /// </summary>
        public static string CadoryxDocumentsFilter {
            get {
                return ResourceManager.GetString("CadoryxDocumentsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadoryx document (*.cadoryx)|*.cadoryx|All files (*.*)|*.*.
        /// </summary>
        public static string CadoryxFilter {
            get {
                return ResourceManager.GetString("CadoryxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadoryx on GitHub.
        /// </summary>
        public static string CadoryxGitHub {
            get {
                return ResourceManager.GetString("CadoryxGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate preview.
        /// </summary>
        public static string CalculatePreview {
            get {
                return ResourceManager.GetString("CalculatePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating preview....
        /// </summary>
        public static string CalculatingPreview {
            get {
                return ResourceManager.GetString("CalculatingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string CanceledStatus {
            get {
                return ResourceManager.GetString("CanceledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear messages.
        /// </summary>
        public static string ClearMessages {
            get {
                return ResourceManager.GetString("ClearMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close document.
        /// </summary>
        public static string CloseDocumentTitle {
            get {
                return ResourceManager.GetString("CloseDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature committed..
        /// </summary>
        public static string CommittedStatus {
            get {
                return ResourceManager.GetString("CommittedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound.
        /// </summary>
        public static string Compound {
            get {
                return ResourceManager.GetString("Compound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the application?.
        /// </summary>
        public static string ConfirmExitMessage {
            get {
                return ResourceManager.GetString("ConfirmExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Confirmation.
        /// </summary>
        public static string ConfirmExitTitle {
            get {
                return ResourceManager.GetString("ConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0}.
        /// </summary>
        public static string CreateBodyFormat {
            get {
                return ResourceManager.GetString("CreateBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation target.
        /// </summary>
        public static string CreationTarget {
            get {
                return ResourceManager.GetString("CreationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder.
        /// </summary>
        public static string Cylinder {
            get {
                return ResourceManager.GetString("Cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default projection.
        /// </summary>
        public static string DefaultProjection {
            get {
                return ResourceManager.GetString("DefaultProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default selection mode.
        /// </summary>
        public static string DefaultSelectionMode {
            get {
                return ResourceManager.GetString("DefaultSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete layer.
        /// </summary>
        public static string DeleteLayer {
            get {
                return ResourceManager.GetString("DeleteLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete material.
        /// </summary>
        public static string DeleteMaterial {
            get {
                return ResourceManager.GetString("DeleteMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density (kg/m³).
        /// </summary>
        public static string DensityKgPerM3 {
            get {
                return ResourceManager.GetString("DensityKgPerM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document resources.
        /// </summary>
        public static string DocumentResources {
            get {
                return ResourceManager.GetString("DocumentResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save.
        /// </summary>
        public static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource with this name already exists..
        /// </summary>
        public static string DuplicateResourceName {
            get {
                return ResourceManager.GetString("DuplicateResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entity properties.
        /// </summary>
        public static string EditEntityProperties {
            get {
                return ResourceManager.GetString("EditEntityProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit feature.
        /// </summary>
        public static string EditFeature {
            get {
                return ResourceManager.GetString("EditFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit feature parameters.
        /// </summary>
        public static string EditFeatureParameters {
            get {
                return ResourceManager.GetString("EditFeatureParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing feature....
        /// </summary>
        public static string EditingFeatureStatus {
            get {
                return ResourceManager.GetString("EditingFeatureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit layer.
        /// </summary>
        public static string EditLayer {
            get {
                return ResourceManager.GetString("EditLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit material.
        /// </summary>
        public static string EditMaterial {
            get {
                return ResourceManager.GetString("EditMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preview available..
        /// </summary>
        public static string EmptyPreviewStatus {
            get {
                return ResourceManager.GetString("EmptyPreviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable preselection.
        /// </summary>
        public static string EnablePreselection {
            get {
                return ResourceManager.GetString("EnablePreselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity name.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported {0} to {1}..
        /// </summary>
        public static string ExportedFormat {
            get {
                return ResourceManager.GetString("ExportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported export formats.
        /// </summary>
        public static string ExportFormats {
            get {
                return ResourceManager.GetString("ExportFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export model.
        /// </summary>
        public static string ExportModelTitle {
            get {
                return ResourceManager.GetString("ExportModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export options.
        /// </summary>
        public static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrude.
        /// </summary>
        public static string Extrude {
            get {
                return ResourceManager.GetString("Extrude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrude / revolve profile.
        /// </summary>
        public static string ExtrudeRevolveProfile {
            get {
                return ResourceManager.GetString("ExtrudeRevolveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature history.
        /// </summary>
        public static string FeatureHistory {
            get {
                return ResourceManager.GetString("FeatureHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first confirmed body creates a part. Use document resources to add more parts..
        /// </summary>
        public static string FirstPartCreatedAutomatically {
            get {
                return ResourceManager.GetString("FirstPartCreatedAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        public static string Fit {
            get {
                return ResourceManager.GetString("Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGES files (*.igs;*.iges)|*.igs;*.iges|All files (*.*)|*.*.
        /// </summary>
        public static string IgesFilter {
            get {
                return ResourceManager.GetString("IgesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGES model (*.igs;*.iges)|*.igs;*.iges.
        /// </summary>
        public static string IgesModelFilter {
            get {
                return ResourceManager.GetString("IgesModelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP, IGES, and STL import/export are supported..
        /// </summary>
        public static string ImportExportSupportMessage {
            get {
                return ResourceManager.GetString("ImportExportSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this instance in its parent&apos;s coordinates. Geometry and other instances stay unchanged..
        /// </summary>
        public static string InstanceLocalCoordinates {
            get {
                return ResourceManager.GetString("InstanceLocalCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance path.
        /// </summary>
        public static string InstancePath {
            get {
                return ResourceManager.GetString("InstancePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance placement.
        /// </summary>
        public static string InstancePlacement {
            get {
                return ResourceManager.GetString("InstancePlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation angle (°).
        /// </summary>
        public static string InstanceRotationAngle {
            get {
                return ResourceManager.GetString("InstanceRotationAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string Interaction {
            get {
                return ResourceManager.GetString("Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection.
        /// </summary>
        public static string Intersection {
            get {
                return ResourceManager.GetString("Intersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings are invalid..
        /// </summary>
        public static string InvalidApplicationSettings {
            get {
                return ResourceManager.GetString("InvalidApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert orbit vertical axis.
        /// </summary>
        public static string InvertOrbitVerticalAxis {
            get {
                return ResourceManager.GetString("InvertOrbitVerticalAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert zoom.
        /// </summary>
        public static string InvertZoom {
            get {
                return ResourceManager.GetString("InvertZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep at least one layer..
        /// </summary>
        public static string LastLayerRequired {
            get {
                return ResourceManager.GetString("LastLayerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer locked.
        /// </summary>
        public static string LayerLocked {
            get {
                return ResourceManager.GetString("LayerLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear deviation.
        /// </summary>
        public static string LinearDeviation {
            get {
                return ResourceManager.GetString("LinearDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local translation X / Y / Z (mm).
        /// </summary>
        public static string LocalTranslation {
            get {
                return ResourceManager.GetString("LocalTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass (kg).
        /// </summary>
        public static string MassKg {
            get {
                return ResourceManager.GetString("MassKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass uses the exact body volume and this density. No material means no mass estimate..
        /// </summary>
        public static string MaterialDensityHint {
            get {
                return ResourceManager.GetString("MaterialDensityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh.
        /// </summary>
        public static string Mesh {
            get {
                return ResourceManager.GetString("Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the visible model using the selected format..
        /// </summary>
        public static string ModelExportSemantics {
            get {
                return ResourceManager.GetString("ModelExportSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model format.
        /// </summary>
        public static string ModelFormat {
            get {
                return ResourceManager.GetString("ModelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeling.
        /// </summary>
        public static string Modeling {
            get {
                return ResourceManager.GetString("Modeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a modeling operation and adjust its parameters..
        /// </summary>
        public static string ModelingInstruction {
            get {
                return ResourceManager.GetString("ModelingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeling parameters.
        /// </summary>
        public static string ModelingParameters {
            get {
                return ResourceManager.GetString("ModelingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an object to inspect its properties..
        /// </summary>
        public static string ModelTreeInstruction {
            get {
                return ResourceManager.GetString("ModelTreeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move instance.
        /// </summary>
        public static string MoveInstance {
            get {
                return ResourceManager.GetString("MoveInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple selection.
        /// </summary>
        public static string MultipleSelection {
            get {
                return ResourceManager.GetString("MultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No material.
        /// </summary>
        public static string NoMaterial {
            get {
                return ResourceManager.GetString("NoMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selection.
        /// </summary>
        public static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCCT Sharp 3D CAD.
        /// </summary>
        public static string OcctSharp3dCad {
            get {
                return ResourceManager.GetString("OcctSharp3dCad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only visible objects.
        /// </summary>
        public static string OnlyVisibleObjects {
            get {
                return ResourceManager.GetString("OnlyVisibleObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cadoryx document.
        /// </summary>
        public static string OpenCadDocumentTitle {
            get {
                return ResourceManager.GetString("OpenCadDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened {0}..
        /// </summary>
        public static string OpenedFormat {
            get {
                return ResourceManager.GetString("OpenedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open / import.
        /// </summary>
        public static string OpenImport {
            get {
                return ResourceManager.GetString("OpenImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbit sensitivity.
        /// </summary>
        public static string OrbitSensitivity {
            get {
                return ResourceManager.GetString("OrbitSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthographic.
        /// </summary>
        public static string Orthographic {
            get {
                return ResourceManager.GetString("Orthographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part definition name.
        /// </summary>
        public static string PartDefinitionName {
            get {
                return ResourceManager.GetString("PartDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perspective.
        /// </summary>
        public static string Perspective {
            get {
                return ResourceManager.GetString("Perspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon extrude.
        /// </summary>
        public static string PolygonExtrude {
            get {
                return ResourceManager.GetString("PolygonExtrude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon revolve.
        /// </summary>
        public static string PolygonRevolve {
            get {
                return ResourceManager.GetString("PolygonRevolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position (X, Y, Z).
        /// </summary>
        public static string PositionXYZ {
            get {
                return ResourceManager.GetString("PositionXYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview ready..
        /// </summary>
        public static string PreviewReadyStatus {
            get {
                return ResourceManager.GetString("PreviewReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary color.
        /// </summary>
        public static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define a profile for the selected operation..
        /// </summary>
        public static string ProfileInstruction {
            get {
                return ResourceManager.GetString("ProfileInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover unsaved work from a previous session. A recovered document opens as an unsaved copy. If the newest snapshot is damaged, the previous completed snapshot will be tried..
        /// </summary>
        public static string RecoveryDescription {
            get {
                return ResourceManager.GetString("RecoveryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard snapshots.
        /// </summary>
        public static string RecoveryDiscard {
            get {
                return ResourceManager.GetString("RecoveryDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all recovery snapshots for “{0}”? This cannot be undone. The original file is not affected..
        /// </summary>
        public static string RecoveryDiscardQuestion {
            get {
                return ResourceManager.GetString("RecoveryDiscardQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recoverable documents. Snapshots belonging to running Cadoryx windows are excluded..
        /// </summary>
        public static string RecoveryEmpty {
            get {
                return ResourceManager.GetString("RecoveryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string RecoveryLater {
            get {
                return ResourceManager.GetString("RecoveryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string RecoveryName {
            get {
                return ResourceManager.GetString("RecoveryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovered as an unsaved copy. Save it to a location of your choice..
        /// </summary>
        public static string RecoveryOpened {
            get {
                return ResourceManager.GetString("RecoveryOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file.
        /// </summary>
        public static string RecoveryOriginalPath {
            get {
                return ResourceManager.GetString("RecoveryOriginalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RecoveryRefresh {
            get {
                return ResourceManager.GetString("RecoveryRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover copy.
        /// </summary>
        public static string RecoveryRestore {
            get {
                return ResourceManager.GetString("RecoveryRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery failed or the workspace is busy. See Messages for details..
        /// </summary>
        public static string RecoveryRestoreFailed {
            get {
                return ResourceManager.GetString("RecoveryRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots.
        /// </summary>
        public static string RecoverySnapshotCount {
            get {
                return ResourceManager.GetString("RecoverySnapshotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot time (UTC).
        /// </summary>
        public static string RecoverySnapshotTime {
            get {
                return ResourceManager.GetString("RecoverySnapshotTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document recovery.
        /// </summary>
        public static string RecoveryTitle {
            get {
                return ResourceManager.GetString("RecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery protection could not be updated: {0}.
        /// </summary>
        public static string RecoveryWriteFailed {
            get {
                return ResourceManager.GetString("RecoveryWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body / feature references:.
        /// </summary>
        public static string ReferenceCount {
            get {
                return ResourceManager.GetString("ReferenceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove point.
        /// </summary>
        public static string RemovePoint {
            get {
                return ResourceManager.GetString("RemovePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied. You can undo this change after closing the window..
        /// </summary>
        public static string ResourceEditApplied {
            get {
                return ResourceManager.GetString("ResourceEditApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource is referenced by bodies or retained feature outputs. Reassign those references before deleting it..
        /// </summary>
        public static string ResourceInUse {
            get {
                return ResourceManager.GetString("ResourceInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name, then add or apply. Each edit takes effect immediately and can be undone in the document. Referenced resources cannot be deleted..
        /// </summary>
        public static string ResourceWindowHint {
            get {
                return ResourceManager.GetString("ResourceWindowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolve.
        /// </summary>
        public static string Revolve {
            get {
                return ResourceManager.GetString("Revolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation angle.
        /// </summary>
        public static string RotationAngle {
            get {
                return ResourceManager.GetString("RotationAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation axis X / Y / Z.
        /// </summary>
        public static string RotationAxis {
            get {
                return ResourceManager.GetString("RotationAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Cadoryx document.
        /// </summary>
        public static string SaveCadoryxDocumentTitle {
            get {
                return ResourceManager.GetString("SaveCadoryxDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to “{0}”?.
        /// </summary>
        public static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0}..
        /// </summary>
        public static string SavedFormat {
            get {
                return ResourceManager.GetString("SavedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary color.
        /// </summary>
        public static string SecondaryColor {
            get {
                return ResourceManager.GetString("SecondaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a part or assembly instance in the model tree..
        /// </summary>
        public static string SelectInstance {
            get {
                return ResourceManager.GetString("SelectInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected.
        /// </summary>
        public static string SelectionSummaryFormat {
            get {
                return ResourceManager.GetString("SelectionSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing layer..
        /// </summary>
        public static string SelectLayer {
            get {
                return ResourceManager.GetString("SelectLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing material..
        /// </summary>
        public static string SelectMaterial {
            get {
                return ResourceManager.GetString("SelectMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a target part..
        /// </summary>
        public static string SelectTargetPart {
            get {
                return ResourceManager.GetString("SelectTargetPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change appearance.
        /// </summary>
        public static string SetAppearance {
            get {
                return ResourceManager.GetString("SetAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        public static string SettingsSavedHint {
            get {
                return ResourceManager.GetString("SettingsSavedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change visibility.
        /// </summary>
        public static string SetVisibility {
            get {
                return ResourceManager.GetString("SetVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaded.
        /// </summary>
        public static string Shaded {
            get {
                return ResourceManager.GetString("Shaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This position belongs to a reused subassembly. Select its parent instance to move a single copy; independent child editing is not available yet..
        /// </summary>
        public static string SharedParentMoveBlocked {
            get {
                return ResourceManager.GetString("SharedParentMoveBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edits to a part definition affect all its instances..
        /// </summary>
        public static string SharedPartEditingHint {
            get {
                return ResourceManager.GetString("SharedPartEditingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        public static string Sheet {
            get {
                return ResourceManager.GetString("Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show axes.
        /// </summary>
        public static string ShowAxes {
            get {
                return ResourceManager.GetString("ShowAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show frames per second.
        /// </summary>
        public static string ShowFramesPerSecond {
            get {
                return ResourceManager.GetString("ShowFramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show view cube.
        /// </summary>
        public static string ShowViewCube {
            get {
                return ResourceManager.GetString("ShowViewCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single selection.
        /// </summary>
        public static string SingleSelection {
            get {
                return ResourceManager.GetString("SingleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size X / radius.
        /// </summary>
        public static string SizeXRadius {
            get {
                return ResourceManager.GetString("SizeXRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Y.
        /// </summary>
        public static string SizeY {
            get {
                return ResourceManager.GetString("SizeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Z / distance.
        /// </summary>
        public static string SizeZDistance {
            get {
                return ResourceManager.GetString("SizeZDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        public static string Solid {
            get {
                return ResourceManager.GetString("Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP files (*.step;*.stp)|*.step;*.stp|All files (*.*)|*.*.
        /// </summary>
        public static string StepFilter {
            get {
                return ResourceManager.GetString("StepFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP model (*.step;*.stp)|*.step;*.stp.
        /// </summary>
        public static string StepModelFilter {
            get {
                return ResourceManager.GetString("StepModelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export a tessellated STL mesh..
        /// </summary>
        public static string StlExportSemantics {
            get {
                return ResourceManager.GetString("StlExportSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STL mesh.
        /// </summary>
        public static string StlMesh {
            get {
                return ResourceManager.GetString("StlMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STL model (*.stl)|*.stl.
        /// </summary>
        public static string StlModelFilter {
            get {
                return ResourceManager.GetString("StlModelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target part.
        /// </summary>
        public static string TargetPart {
            get {
                return ResourceManager.GetString("TargetPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tool to begin..
        /// </summary>
        public static string ToolStatusHint {
            get {
                return ResourceManager.GetString("ToolStatusHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Union.
        /// </summary>
        public static string Union {
            get {
                return ResourceManager.GetString("Union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeter.
        /// </summary>
        public static string UnitMillimeter {
            get {
                return ResourceManager.GetString("UnitMillimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document type is read-only..
        /// </summary>
        public static string UnsupportedDocumentReadOnly {
            get {
                return ResourceManager.GetString("UnsupportedDocumentReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature cannot be edited yet..
        /// </summary>
        public static string UnsupportedFeatureEdit {
            get {
                return ResourceManager.GetString("UnsupportedFeatureEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled {0}.
        /// </summary>
        public static string UntitledDocumentFormat {
            get {
                return ResourceManager.GetString("UntitledDocumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use as modeling target.
        /// </summary>
        public static string UseAsTargetPart {
            get {
                return ResourceManager.GetString("UseAsTargetPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use dark theme.
        /// </summary>
        public static string UseDarkTheme {
            get {
                return ResourceManager.GetString("UseDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewport.
        /// </summary>
        public static string Viewport {
            get {
                return ResourceManager.GetString("Viewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left drag: rotate · Middle drag: pan · Wheel: zoom.
        /// </summary>
        public static string ViewportInteractionHint {
            get {
                return ResourceManager.GetString("ViewportInteractionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window selection.
        /// </summary>
        public static string WindowSelection {
            get {
                return ResourceManager.GetString("WindowSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire.
        /// </summary>
        public static string Wire {
            get {
                return ResourceManager.GetString("Wire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe.
        /// </summary>
        public static string Wireframe {
            get {
                return ResourceManager.GetString("Wireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeling workspace.
        /// </summary>
        public static string WorkspaceModeling {
            get {
                return ResourceManager.GetString("WorkspaceModeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ready. Create or open a document to begin..
        /// </summary>
        public static string WorkspaceReadyMessage {
            get {
                return ResourceManager.GetString("WorkspaceReadyMessage", resourceCulture);
            }
        }
    }
}
