//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadoryx.Lang.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cadoryx.Lang.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add point 的本地化字符串。
        /// </summary>
        public static string AddPoint {
            get {
                return ResourceManager.GetString("AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always on top 的本地化字符串。
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angular deviation 的本地化字符串。
        /// </summary>
        public static string AngularDeviation {
            get {
                return ResourceManager.GetString("AngularDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antialiasing 的本地化字符串。
        /// </summary>
        public static string Antialiasing {
            get {
                return ResourceManager.GetString("Antialiasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Settings 的本地化字符串。
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application settings applied. 的本地化字符串。
        /// </summary>
        public static string ApplicationSettingsApplied {
            get {
                return ResourceManager.GetString("ApplicationSettingsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply properties 的本地化字符串。
        /// </summary>
        public static string ApplyProperties {
            get {
                return ResourceManager.GetString("ApplyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly 的本地化字符串。
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 的本地化字符串。
        /// </summary>
        public static string AxisX {
            get {
                return ResourceManager.GetString("AxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y 的本地化字符串。
        /// </summary>
        public static string AxisY {
            get {
                return ResourceManager.GetString("AxisY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axonometric 的本地化字符串。
        /// </summary>
        public static string Axonometric {
            get {
                return ResourceManager.GetString("Axonometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background color 的本地化字符串。
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary STL 的本地化字符串。
        /// </summary>
        public static string BinaryStl {
            get {
                return ResourceManager.GetString("BinaryStl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a feature and choose a boolean operation. 的本地化字符串。
        /// </summary>
        public static string BooleanInstruction {
            get {
                return ResourceManager.GetString("BooleanInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum bounds 的本地化字符串。
        /// </summary>
        public static string BoundsMaximum {
            get {
                return ResourceManager.GetString("BoundsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum bounds 的本地化字符串。
        /// </summary>
        public static string BoundsMinimum {
            get {
                return ResourceManager.GetString("BoundsMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Box 的本地化字符串。
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By layer 的本地化字符串。
        /// </summary>
        public static string ByLayer {
            get {
                return ResourceManager.GetString("ByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cadoryx 的本地化字符串。
        /// </summary>
        public static string Cadoryx {
            get {
                return ResourceManager.GetString("Cadoryx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cadoryx document (*.cadoryx)|*.cadoryx 的本地化字符串。
        /// </summary>
        public static string CadoryxDocumentFilter {
            get {
                return ResourceManager.GetString("CadoryxDocumentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cadoryx documents (*.cadoryx)|*.cadoryx|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string CadoryxDocumentsFilter {
            get {
                return ResourceManager.GetString("CadoryxDocumentsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cadoryx document (*.cadoryx)|*.cadoryx|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string CadoryxFilter {
            get {
                return ResourceManager.GetString("CadoryxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cadoryx on GitHub 的本地化字符串。
        /// </summary>
        public static string CadoryxGitHub {
            get {
                return ResourceManager.GetString("CadoryxGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculate preview 的本地化字符串。
        /// </summary>
        public static string CalculatePreview {
            get {
                return ResourceManager.GetString("CalculatePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculating preview... 的本地化字符串。
        /// </summary>
        public static string CalculatingPreview {
            get {
                return ResourceManager.GetString("CalculatingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceled 的本地化字符串。
        /// </summary>
        public static string CanceledStatus {
            get {
                return ResourceManager.GetString("CanceledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear messages 的本地化字符串。
        /// </summary>
        public static string ClearMessages {
            get {
                return ResourceManager.GetString("ClearMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close document 的本地化字符串。
        /// </summary>
        public static string CloseDocumentTitle {
            get {
                return ResourceManager.GetString("CloseDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature committed. 的本地化字符串。
        /// </summary>
        public static string CommittedStatus {
            get {
                return ResourceManager.GetString("CommittedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compound 的本地化字符串。
        /// </summary>
        public static string Compound {
            get {
                return ResourceManager.GetString("Compound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to exit the application? 的本地化字符串。
        /// </summary>
        public static string ConfirmExitMessage {
            get {
                return ResourceManager.GetString("ConfirmExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Confirmation 的本地化字符串。
        /// </summary>
        public static string ConfirmExitTitle {
            get {
                return ResourceManager.GetString("ConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created {0} 的本地化字符串。
        /// </summary>
        public static string CreateBodyFormat {
            get {
                return ResourceManager.GetString("CreateBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cylinder 的本地化字符串。
        /// </summary>
        public static string Cylinder {
            get {
                return ResourceManager.GetString("Cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default projection 的本地化字符串。
        /// </summary>
        public static string DefaultProjection {
            get {
                return ResourceManager.GetString("DefaultProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default selection mode 的本地化字符串。
        /// </summary>
        public static string DefaultSelectionMode {
            get {
                return ResourceManager.GetString("DefaultSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difference 的本地化字符串。
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit entity properties 的本地化字符串。
        /// </summary>
        public static string EditEntityProperties {
            get {
                return ResourceManager.GetString("EditEntityProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit feature 的本地化字符串。
        /// </summary>
        public static string EditFeature {
            get {
                return ResourceManager.GetString("EditFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit feature parameters 的本地化字符串。
        /// </summary>
        public static string EditFeatureParameters {
            get {
                return ResourceManager.GetString("EditFeatureParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editing feature... 的本地化字符串。
        /// </summary>
        public static string EditingFeatureStatus {
            get {
                return ResourceManager.GetString("EditingFeatureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty 的本地化字符串。
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No preview available. 的本地化字符串。
        /// </summary>
        public static string EmptyPreviewStatus {
            get {
                return ResourceManager.GetString("EmptyPreviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable preselection 的本地化字符串。
        /// </summary>
        public static string EnablePreselection {
            get {
                return ResourceManager.GetString("EnablePreselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity name 的本地化字符串。
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported {0} to {1}. 的本地化字符串。
        /// </summary>
        public static string ExportedFormat {
            get {
                return ResourceManager.GetString("ExportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supported export formats 的本地化字符串。
        /// </summary>
        public static string ExportFormats {
            get {
                return ResourceManager.GetString("ExportFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export model 的本地化字符串。
        /// </summary>
        public static string ExportModelTitle {
            get {
                return ResourceManager.GetString("ExportModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export options 的本地化字符串。
        /// </summary>
        public static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extrude 的本地化字符串。
        /// </summary>
        public static string Extrude {
            get {
                return ResourceManager.GetString("Extrude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extrude / revolve profile 的本地化字符串。
        /// </summary>
        public static string ExtrudeRevolveProfile {
            get {
                return ResourceManager.GetString("ExtrudeRevolveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature history 的本地化字符串。
        /// </summary>
        public static string FeatureHistory {
            get {
                return ResourceManager.GetString("FeatureHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit 的本地化字符串。
        /// </summary>
        public static string Fit {
            get {
                return ResourceManager.GetString("Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Front 的本地化字符串。
        /// </summary>
        public static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IGES files (*.igs;*.iges)|*.igs;*.iges|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string IgesFilter {
            get {
                return ResourceManager.GetString("IgesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IGES model (*.igs;*.iges)|*.igs;*.iges 的本地化字符串。
        /// </summary>
        public static string IgesModelFilter {
            get {
                return ResourceManager.GetString("IgesModelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STEP, IGES, and STL import/export are supported. 的本地化字符串。
        /// </summary>
        public static string ImportExportSupportMessage {
            get {
                return ResourceManager.GetString("ImportExportSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance path 的本地化字符串。
        /// </summary>
        public static string InstancePath {
            get {
                return ResourceManager.GetString("InstancePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interaction 的本地化字符串。
        /// </summary>
        public static string Interaction {
            get {
                return ResourceManager.GetString("Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intersection 的本地化字符串。
        /// </summary>
        public static string Intersection {
            get {
                return ResourceManager.GetString("Intersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application settings are invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidApplicationSettings {
            get {
                return ResourceManager.GetString("InvalidApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert orbit vertical axis 的本地化字符串。
        /// </summary>
        public static string InvertOrbitVerticalAxis {
            get {
                return ResourceManager.GetString("InvertOrbitVerticalAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert zoom 的本地化字符串。
        /// </summary>
        public static string InvertZoom {
            get {
                return ResourceManager.GetString("InvertZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日本語 的本地化字符串。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layer 的本地化字符串。
        /// </summary>
        public static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layer locked 的本地化字符串。
        /// </summary>
        public static string LayerLocked {
            get {
                return ResourceManager.GetString("LayerLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linear deviation 的本地化字符串。
        /// </summary>
        public static string LinearDeviation {
            get {
                return ResourceManager.GetString("LinearDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material 的本地化字符串。
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mesh 的本地化字符串。
        /// </summary>
        public static string Mesh {
            get {
                return ResourceManager.GetString("Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messages 的本地化字符串。
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the visible model using the selected format. 的本地化字符串。
        /// </summary>
        public static string ModelExportSemantics {
            get {
                return ResourceManager.GetString("ModelExportSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model format 的本地化字符串。
        /// </summary>
        public static string ModelFormat {
            get {
                return ResourceManager.GetString("ModelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modeling 的本地化字符串。
        /// </summary>
        public static string Modeling {
            get {
                return ResourceManager.GetString("Modeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a modeling operation and adjust its parameters. 的本地化字符串。
        /// </summary>
        public static string ModelingInstruction {
            get {
                return ResourceManager.GetString("ModelingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modeling parameters 的本地化字符串。
        /// </summary>
        public static string ModelingParameters {
            get {
                return ResourceManager.GetString("ModelingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an object to inspect its properties. 的本地化字符串。
        /// </summary>
        public static string ModelTreeInstruction {
            get {
                return ResourceManager.GetString("ModelTreeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move instance 的本地化字符串。
        /// </summary>
        public static string MoveInstance {
            get {
                return ResourceManager.GetString("MoveInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple selection 的本地化字符串。
        /// </summary>
        public static string MultipleSelection {
            get {
                return ResourceManager.GetString("MultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No selection 的本地化字符串。
        /// </summary>
        public static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCCT Sharp 3D CAD 的本地化字符串。
        /// </summary>
        public static string OcctSharp3dCad {
            get {
                return ResourceManager.GetString("OcctSharp3dCad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only visible objects 的本地化字符串。
        /// </summary>
        public static string OnlyVisibleObjects {
            get {
                return ResourceManager.GetString("OnlyVisibleObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Cadoryx document 的本地化字符串。
        /// </summary>
        public static string OpenCadDocumentTitle {
            get {
                return ResourceManager.GetString("OpenCadDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opened {0}. 的本地化字符串。
        /// </summary>
        public static string OpenedFormat {
            get {
                return ResourceManager.GetString("OpenedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open / import 的本地化字符串。
        /// </summary>
        public static string OpenImport {
            get {
                return ResourceManager.GetString("OpenImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orbit sensitivity 的本地化字符串。
        /// </summary>
        public static string OrbitSensitivity {
            get {
                return ResourceManager.GetString("OrbitSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orthographic 的本地化字符串。
        /// </summary>
        public static string Orthographic {
            get {
                return ResourceManager.GetString("Orthographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part 的本地化字符串。
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perspective 的本地化字符串。
        /// </summary>
        public static string Perspective {
            get {
                return ResourceManager.GetString("Perspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polygon extrude 的本地化字符串。
        /// </summary>
        public static string PolygonExtrude {
            get {
                return ResourceManager.GetString("PolygonExtrude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polygon revolve 的本地化字符串。
        /// </summary>
        public static string PolygonRevolve {
            get {
                return ResourceManager.GetString("PolygonRevolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position (X, Y, Z) 的本地化字符串。
        /// </summary>
        public static string PositionXYZ {
            get {
                return ResourceManager.GetString("PositionXYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview ready. 的本地化字符串。
        /// </summary>
        public static string PreviewReadyStatus {
            get {
                return ResourceManager.GetString("PreviewReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary color 的本地化字符串。
        /// </summary>
        public static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Define a profile for the selected operation. 的本地化字符串。
        /// </summary>
        public static string ProfileInstruction {
            get {
                return ResourceManager.GetString("ProfileInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove point 的本地化字符串。
        /// </summary>
        public static string RemovePoint {
            get {
                return ResourceManager.GetString("RemovePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Revolve 的本地化字符串。
        /// </summary>
        public static string Revolve {
            get {
                return ResourceManager.GetString("Revolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation angle 的本地化字符串。
        /// </summary>
        public static string RotationAngle {
            get {
                return ResourceManager.GetString("RotationAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As... 的本地化字符串。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Cadoryx document 的本地化字符串。
        /// </summary>
        public static string SaveCadoryxDocumentTitle {
            get {
                return ResourceManager.GetString("SaveCadoryxDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes to “{0}”? 的本地化字符串。
        /// </summary>
        public static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved {0}. 的本地化字符串。
        /// </summary>
        public static string SavedFormat {
            get {
                return ResourceManager.GetString("SavedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary color 的本地化字符串。
        /// </summary>
        public static string SecondaryColor {
            get {
                return ResourceManager.GetString("SecondaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} selected 的本地化字符串。
        /// </summary>
        public static string SelectionSummaryFormat {
            get {
                return ResourceManager.GetString("SelectionSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change appearance 的本地化字符串。
        /// </summary>
        public static string SetAppearance {
            get {
                return ResourceManager.GetString("SetAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings saved. 的本地化字符串。
        /// </summary>
        public static string SettingsSavedHint {
            get {
                return ResourceManager.GetString("SettingsSavedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change visibility 的本地化字符串。
        /// </summary>
        public static string SetVisibility {
            get {
                return ResourceManager.GetString("SetVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shaded 的本地化字符串。
        /// </summary>
        public static string Shaded {
            get {
                return ResourceManager.GetString("Shaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sheet 的本地化字符串。
        /// </summary>
        public static string Sheet {
            get {
                return ResourceManager.GetString("Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show axes 的本地化字符串。
        /// </summary>
        public static string ShowAxes {
            get {
                return ResourceManager.GetString("ShowAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show frames per second 的本地化字符串。
        /// </summary>
        public static string ShowFramesPerSecond {
            get {
                return ResourceManager.GetString("ShowFramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show view cube 的本地化字符串。
        /// </summary>
        public static string ShowViewCube {
            get {
                return ResourceManager.GetString("ShowViewCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single selection 的本地化字符串。
        /// </summary>
        public static string SingleSelection {
            get {
                return ResourceManager.GetString("SingleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size X / radius 的本地化字符串。
        /// </summary>
        public static string SizeXRadius {
            get {
                return ResourceManager.GetString("SizeXRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size Y 的本地化字符串。
        /// </summary>
        public static string SizeY {
            get {
                return ResourceManager.GetString("SizeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size Z / distance 的本地化字符串。
        /// </summary>
        public static string SizeZDistance {
            get {
                return ResourceManager.GetString("SizeZDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solid 的本地化字符串。
        /// </summary>
        public static string Solid {
            get {
                return ResourceManager.GetString("Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STEP files (*.step;*.stp)|*.step;*.stp|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string StepFilter {
            get {
                return ResourceManager.GetString("StepFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STEP model (*.step;*.stp)|*.step;*.stp 的本地化字符串。
        /// </summary>
        public static string StepModelFilter {
            get {
                return ResourceManager.GetString("StepModelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export a tessellated STL mesh. 的本地化字符串。
        /// </summary>
        public static string StlExportSemantics {
            get {
                return ResourceManager.GetString("StlExportSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STL mesh 的本地化字符串。
        /// </summary>
        public static string StlMesh {
            get {
                return ResourceManager.GetString("StlMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STL model (*.stl)|*.stl 的本地化字符串。
        /// </summary>
        public static string StlModelFilter {
            get {
                return ResourceManager.GetString("StlModelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a tool to begin. 的本地化字符串。
        /// </summary>
        public static string ToolStatusHint {
            get {
                return ResourceManager.GetString("ToolStatusHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 的本地化字符串。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transform 的本地化字符串。
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Union 的本地化字符串。
        /// </summary>
        public static string Union {
            get {
                return ResourceManager.GetString("Union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Millimeter 的本地化字符串。
        /// </summary>
        public static string UnitMillimeter {
            get {
                return ResourceManager.GetString("UnitMillimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This document type is read-only. 的本地化字符串。
        /// </summary>
        public static string UnsupportedDocumentReadOnly {
            get {
                return ResourceManager.GetString("UnsupportedDocumentReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature cannot be edited yet. 的本地化字符串。
        /// </summary>
        public static string UnsupportedFeatureEdit {
            get {
                return ResourceManager.GetString("UnsupportedFeatureEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untitled {0} 的本地化字符串。
        /// </summary>
        public static string UntitledDocumentFormat {
            get {
                return ResourceManager.GetString("UntitledDocumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use dark theme 的本地化字符串。
        /// </summary>
        public static string UseDarkTheme {
            get {
                return ResourceManager.GetString("UseDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Viewport 的本地化字符串。
        /// </summary>
        public static string Viewport {
            get {
                return ResourceManager.GetString("Viewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left drag: rotate · Middle drag: pan · Wheel: zoom 的本地化字符串。
        /// </summary>
        public static string ViewportInteractionHint {
            get {
                return ResourceManager.GetString("ViewportInteractionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible 的本地化字符串。
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window selection 的本地化字符串。
        /// </summary>
        public static string WindowSelection {
            get {
                return ResourceManager.GetString("WindowSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wire 的本地化字符串。
        /// </summary>
        public static string Wire {
            get {
                return ResourceManager.GetString("Wire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wireframe 的本地化字符串。
        /// </summary>
        public static string Wireframe {
            get {
                return ResourceManager.GetString("Wireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modeling workspace 的本地化字符串。
        /// </summary>
        public static string WorkspaceModeling {
            get {
                return ResourceManager.GetString("WorkspaceModeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workspace ready. Create or open a document to begin. 的本地化字符串。
        /// </summary>
        public static string WorkspaceReadyMessage {
            get {
                return ResourceManager.GetString("WorkspaceReadyMessage", resourceCulture);
            }
        }
    }
}
